### ISSUE TITLE
App crashed most of the time

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#761] opened 2019-04-23 06:58 UTC
Users say the app is annoying.
- The app crashed when using it.
- Shows eSteem is not responding.

I experience these issues too. It was like the app was degraded to previous version cuz it started the crash issues unnoticed. I had uninstall and install again but it worsen the situation. 

![](https://i.ibb.co/vs1Ddxq/Screenshot-2019-04-25-08-11-20.png)

**Comment by feruzm** [comment] 2019-05-01 08:17
Need more details to work out what causing this. But new release is coming out this week. Please update this issue if you still get crashes, we have to find out the cause.

**Comment by mistikk** [comment] 2019-05-09 10:48
can you share more details? @horpeyloaded

**Comment by feruzm** [comment] 2019-05-10 09:09
probably related to number of issues reported. we know by now some of the causes, so I will close this and we keep track on other individual issues which has more details.

**Closed by feruzm** 2019-05-10 09:09 UTC
Labels: bug, high

**Comment by horpeyloaded** [comment] 2019-05-10 09:10
I'm closing this for now, I will examine thoroughly to know how the app crashes or forced stop other than the reported issues on crashing.
